name: beeman
description: "BeeMan - BeeBox Pollination Management App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  firebase_auth: ^4.16.0
  
  # Firebase packages
  firebase_core: ^2.32.0
  # firebase_auth: ^4.15.3  # Commented out as it's causing issues
  cloud_firestore: ^4.17.5
  # firebase_functions: ^4.5.8  # Commented out as it's causing issues
  # firebase_storage: ^11.5.6  # Commented out as it's causing issues
  
  # Authentication
  google_sign_in: ^6.3.0
  
  # State management
  provider: ^6.1.1
  
  # UI components
  flutter_svg: ^2.0.9
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  
  # Payment integration
  razorpay_flutter: ^1.3.5
  
  # Utilities
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  http: ^1.1.2
  
  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
